# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/xiaomi/mithorium-common-graphics/LA.UM.9.6.3.r1-04400-89xx.0/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/xiaomi/mititanium-common-qc/LA.UM.9.6.3.r1-04400-89xx.0

PRODUCT_COPY_FILES += \
    

PRODUCT_PACKAGES += \
    
